### ISSUE TITLE
Use other model

### ISSUE THREAD

**Issue by zhaobingbingbing** [hiveml/tensorflow-grad-cam#4]
Hi,can I ask if want to use other model,for example Inception-ResNet-v2, can I directly download inception_resnet_v2_2016_08_30.tar.gz,and modify the input arguments in main.sh,then it will works, or I need to rewritite the Script in "model--nets"folder?

**Comment by ryanjay0** [comment]
You will need to download the inception_resnet_v2 slim version [here](https://github.com/tensorflow/models/blob/master/research/slim/nets/inception_resnet_v2.py) to put in the model/nets folder and then add an entry in _layer_names in main.py for the predictions and prepooling layer as Predictions (upper-case). Then for prepooling you'll have to change the inception_resnet_v2.py code to add the line `end_points['PrePool'] = net` right before global pooling at [here](https://github.com/tensorflow/models/blob/3cb798fe02c9c627541e1d7f1816240a17dd02f3/research/slim/nets/inception_resnet_v2.py#L346). 

You also have to add entries for inception resnet v2 in the `nets_factory.py` and `preprocessing_factory.py`. I'd use the provided inception preprocessing for inception resnet v2 also.
